"""empty message

Revision ID: 74c41864ebd6
Revises: cedb26bf96c9
Create Date: 2020-09-29 09:27:55.219811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c41864ebd6'
down_revision = 'cedb26bf96c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'event', ['_id'])
    op.create_unique_constraint(None, 'metadata', ['indicator'])
    op.create_unique_constraint(None, 'news', ['_id'])
    op.create_unique_constraint(None, 'publications', ['_id'])
    op.create_unique_constraint(None, 'sector', ['_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sector', type_='unique')
    op.drop_constraint(None, 'publications', type_='unique')
    op.drop_constraint(None, 'news', type_='unique')
    op.drop_constraint(None, 'metadata', type_='unique')
    op.drop_constraint(None, 'event', type_='unique')
    # ### end Alembic commands ###
